version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 096664318411.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - docker build -t noderepo .

  post_build:
    commands:
      - docker tag noderepo:latest 096664318411.dkr.ecr.ap-south-1.amazonaws.com/noderepo:latest
      - docker push 096664318411.dkr.ecr.ap-south-1.amazonaws.com/noderepo:latest

artifacts:
  files:
    - '**/*'
