version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
      nodejs: 10
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/j1s3u6g4
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t appnoderepo .    
      - echo Tagging the Docker image...
      - docker tag appnoderepo:latest public.ecr.aws/j1s3u6g4/appnoderepo:latest
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push public.ecr.aws/j1s3u6g4/appnoderepo:latest
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' appnoderepo 096664318411.dkr.ecr.us-east-1.amazonaws.com/appnoderepo:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json

