version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 096664318411.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t noderepo .
      - echo Tagging the Docker image...
      - docker tag noderepo:latest 096664318411.dkr.ecr.ap-south-1.amazonaws.com/noderepo:latest
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 096664318411.dkr.ecr.ap-south-1.amazonaws.com/noderepo:latest
      - echo Writing image definitions file...
      - printf '[{"name":"noderepo","imageUri":"%s"}]' $noderepo:latest 096664318411.dkr.ecr.ap-south-1.amazonaws.com/noderepo:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
